project_urls:
  Bug Tracker: https://github.com/AllenCellModeling/napari-aicsimageio/issues
  Documentation: https://github.com/AllenCellModeling/napari-aicsimageio#README.md
  Source Code: https://github.com/AllenCellModeling/napari-aicsimageio
  User Support: https://github.com/AllenCellModeling/napari-aicsimageio/issues