name: Test and Lint

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        os: [
          ubuntu-18.04,
          ubuntu-20.04,
          windows-latest,
          macOS-10.15,
        ]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    # Install qt support libs
    - uses: tlambert03/setup-qt-libs@v1

    strategy borrowed from vispy for installing opengl libs on windows
    - name: Install Windows OpenGL
      if: runner.os == 'Windows'
      run: |
        git clone --depth 1 https://github.com/pyvista/gl-ci-helpers.git
        powershell gl-ci-helpers/appveyor/install_opengl.ps1
        if (Test-Path -Path "C:\Windows\system32\opengl32.dll" -PathType Leaf) {Exit 0} else {Exit 1}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test] 

    - name: Download Test Resources
      run: |
        python scripts/download_test_resources.py

    - name: Test with pytest
      uses: GabrielBB/xvfb-action@v1
      with:
        run: python -m pytest --cov-report xml --cov=napari_aicsimageio napari_aicsimageio/tests/
    - name: Upload codecov
      uses: codecov/codecov-action@v1

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with flake8
      run: |
        flake8 napari_aicsimageio --count --verbose --show-source --statistics
        isort napari_aicsimageio --check-only
        mypy napari_aicsimageio
        black --check --exclude vendor napari_aicsimageio
